// client/src/components/Modal/ModalBox.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, Transition } from 'vue';
import CloseButton from '../Button/CloseButton.vue';

type Props = {
  title?: string;
  open?: boolean;
  onClose?: () => void | boolean | Promise<void | boolean>;
};
const props = defineProps<Props>();

function closeOnEsc(e: KeyboardEvent) {
  if (e.key === 'Escape') {
    e.preventDefault();
    if (props.onClose) props.onClose();
  }
}
onMounted(() => window.addEventListener('keydown', closeOnEsc));
onUnmounted(() => window.removeEventListener('keydown', closeOnEsc));
</script>

<template>
  <Teleport to="body">
    <Transition name="fade">
      <div v-show="open">
        <div class="modal">
          <span class="modal-header">
            <h3>{{ title }}</h3>
            <CloseButton :on-close="onClose" />
          </span>
          <slot />
        </div>
        <div class="modal-backdrop" />
      </div>
    </Transition>
  </Teleport>
</template>

<style>
@import url('./style.css');
</style>

// client/src/components/Modal/ModalBox.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import { fade } from 'svelte/transition';
  import CloseButton from '../Button/CloseButton.svelte';

  export let title: string = '';
  export let open: boolean;
  export let onClose: () => void | boolean | Promise<void | boolean> = () => {};

  function closeOnEsc(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      e.preventDefault();
      onClose();
    }
  }
  onMount(() => window.addEventListener('keydown', closeOnEsc));
  onDestroy(() => window.removeEventListener('keydown', closeOnEsc));
</script>

{#if open}
  <div transition:fade={{ duration: 150 }}>
    <div
      class="modal"
      on:click|stopPropagation
      on:keydown={() => {}}
    >
      <span class="modal-header">
        <h3>{title}</h3>
        <CloseButton {onClose} />
      </span>
      <slot />
    </div>
    <div class="modal-backdrop" />
  </div>
{/if}

<style>
  @import url('./style.css');
</style>
