// client/src/components/Modal/index.tsx
import './style.css';
import React, { ReactNode, KeyboardEvent, useRef } from 'react';
import ReactDOM from 'react-dom';
import { Button } from '../Button';

type Props = {
  title: string;
  open: boolean;
  onClose: () => void | boolean | Promise<void | boolean>;
  classAnimation: string
};
type DefaultProps = Props & {
  content: string;
};
type CustomizableProps = Props & {
  children: ReactNode;
};
type CustomizableContentProps = {
  children: ReactNode;
};
type CustomizableActionProps = {
  children: ReactNode;
};

const ESCAPE = 'Escape'

export const Modal = {
  Default: ({ open, title, content, onClose }: Partial<DefaultProps>) => {
    function closeOnEsc(e: KeyboardEvent) {
      if (e.key === ESCAPE) {
        e.preventDefault()
        if (onClose)
          onClose()
      }
    }

    return ReactDOM.createPortal(
      <React.Fragment>
        {open && (
          <>
            <div className='modal' onKeyDown={closeOnEsc}>
              <span className='modal-header'>
                <h3>{title}</h3>
                <Button.Close onClose={onClose} />
              </span>
              <div className='modal-body'>
                <p>{content}</p>
              </div>
              <div className='modal-footer'>
                <Button.Accept
                  label='Accept'
                  onAccept={onClose}
                />
                <Button.Cancel
                  label='Cancel'
                  onCancel={onClose}
                />
              </div>
            </div>
            <div className='modal-backdrop' />
          </>
        )}
      </React.Fragment>,
      document.querySelector('body') as HTMLElement,
    );
  },
  Customizable: ({
    open,
    onClose,
    title,
    children,
    classAnimation
  }: CustomizableProps) => {
    const modal = useRef<HTMLDivElement>(null)
    modal.current?.focus()

    return ReactDOM.createPortal(
      <React.Fragment>
        {open && (
          <>
            <div ref={modal} className={`modal ${classAnimation}`}>
              <span className='modal-header'>
                <h3>{title}</h3>
                <Button.Close onClose={onClose} />
              </span>
              {children}
            </div>
            <div className='modal-backdrop' />
          </>
        )}
      </React.Fragment>,
      document.querySelector('body') as HTMLElement,
    )
  },
  ContentBody: ({ children }: Partial<CustomizableContentProps>) => (
    <div className='modal-body'>{children}</div>
  ),
  ActionFooter: ({ children }: Partial<CustomizableActionProps>) => (
    <div className='modal-footer'>{children}</div>
  ),
};

// client/src/components/Modal/Modal.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import SecondaryButton from '../SecondaryButton.vue';

interface IModal {
  title?: string;
  open?: boolean;
  name?: string;
  onClose?: () => void | Promise<void>;
}
const { onClose } = defineProps<IModal>();
const modal = ref<HTMLDivElement | null>(null);
const ESCAPE = 'Escape';
function closeOnEsc(e: KeyboardEvent) {
  if (e.key === ESCAPE) {
    e.preventDefault();
    onClose!();
  }
}
onMounted(() => {
  if (!modal.value) return;
  modal.value.focus();
  modal.value.addEventListener('focus', (e: Event) => {
    e.stopPropagation();
  });
  window.addEventListener('keydown', closeOnEsc);
});
onUnmounted(() => {
  if (!modal.value) return;
  modal.value.removeEventListener('focus', (e: Event) => {
    e.stopPropagation();
  });
  window.removeEventListener('keydown', closeOnEsc);
});
</script>

<template>
  <Teleport to="body">
    <Transition name="md-fade">
      <div
        v-if="open"
        :id="name"
      >
        <div
          id="modal"
          ref="modal"
        >
          <span class="modal-header">
            <h3>{{ title }}</h3>
            <SecondaryButton
              no-content
              @action="onClose"
            />
          </span>
          <slot />
        </div>
      </div>
    </Transition>
    <div
      v-if="open"
      class="modal-backdrop"
      @click="onClose"
    />
  </Teleport>
</template>

<style>
@import url('./style.css');
</style>
