// client/src/App.svelte
<script lang="ts">
  import { useAuth } from './services';
  import { Route, useLocation, useNavigate } from 'svelte-navigator';
  import LoginOrRegistrate from './layouts/LoginOrRegistrate.svelte';
  import ChatApp from './layouts/ChatApp.svelte';
  import { onMount } from 'svelte';

  const { accessToken, isAuth } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();

  onMount(() => {
    if ((isAuth || accessToken) && $location.pathname === '/')
      navigate('/chat');
    if ((!isAuth || !accessToken) && $location.pathname === '/') navigate('/');
  });
</script>

<Route
  path="/"
  primary={false}
>
  <LoginOrRegistrate />
</Route>
<Route
  path="/chat/*"
  primary={false}
>
  <ChatApp />
</Route>

// client/src/App.vue
<script setup lang="ts">
import Chat from './views/Chat/Chat.vue';
import LoginOrRegistrate from './views/LoginOrRegistrate/LoginOrRegistrate.vue';
import { useAuth } from './services';
const { isAuth } = useAuth();
</script>

<template>
  <LoginOrRegistrate v-if="!isAuth" />
  <Chat v-else />
</template>
