// client/src/components/PageHeader.vue
<script setup lang="ts">
import Avatar from './Avatar.vue';

interface IPageHeader {
  author?: string;
  avatarSrc?: string;
}
defineProps<IPageHeader>();
</script>

<template>
  <div class="page-header">
    <Avatar
      v-if="!avatarSrc"
      no-avatar
      :name="author"
    />
    <Avatar
      v-else
      :src="avatarSrc"
      alt="#"
    />
    <h2>{{ author }}</h2>
  </div>
</template>

<style scoped>
@import url('../assets/color.css');

.page-header {
  background: var(--darker-bg);
  display: flex;
  justify-content: flex-start;
  align-items: center;
  height: 10vh;
  padding-left: 0.5rem;
  gap: 1rem;
}

.page-header > h2 {
  border-radius: 10px;
  padding: 0.5rem;
}
</style>

// client/src/components/PageHeader/PageHeader.svelte
<script lang="ts">
  import LabelAvatar from '../Avatar/LabelAvatar.svelte';
  import NoneLabelAvatar from '../Avatar/NoneLabelAvatar.svelte';

  export let author: string = '';
  export let avatarSrc: string = '';
</script>

<template>
  <div class="page-header">
    {#if avatarSrc}
      <LabelAvatar
        src={avatarSrc}
        alt={avatarSrc}
      />
    {/if}
    {#if !avatarSrc}
      <NoneLabelAvatar name="T" />
    {/if}
    <h2>{author}</h2>
  </div>
</template>

<style>
  @import url('./style.css');
</style>
