// client/src/components/PageHeader/index.tsx
import { Avatar } from '../Avatar'
import './style.css'

type Props = {
  author: string
  avatarSrc: string
}

export const PageHeader = ({ author, avatarSrc }: Props) => {
  return (
    <div className="page-header">
      {
        !avatarSrc
          ? <Avatar.WithoutLabel name='A du' />
          : <Avatar.WithLabel src={avatarSrc} alt={avatarSrc} />
      }
      <h2>{author}</h2>
    </div>
  );
};

// client/src/components/PageHeader/PageHeader.vue
<script setup lang="ts">
import LabelAvatar from '../Avatar/LabelAvatar.vue';
import NoneLabelAvatar from '../Avatar/NoneLabelAvatar.vue';

type Props = {
  author?: string;
  avatarSrc?: string;
};
defineProps<Props>();
</script>

<template>
  <div class="page-header">
    <LabelAvatar
      v-if="avatarSrc"
      :src="avatarSrc"
      :alt="avatarSrc"
    />
    <NoneLabelAvatar
      v-else
      name="T"
    />
    <h2>{{ author }}</h2>
  </div>
</template>

<style scoped>
@import url('./style.css');
</style>
