// client/src/components/PageHeader/PageHeader.svelte
<script lang="ts">
  import LabelAvatar from '../Avatar/LabelAvatar.svelte';
  import NoneLabelAvatar from '../Avatar/NoneLabelAvatar.svelte';

  export let author: string = '';
  export let avatarSrc: string = '';
</script>

<template>
  <div class="page-header">
    {#if avatarSrc}
      <LabelAvatar
        src={avatarSrc}
        alt={avatarSrc}
      />
    {/if}
    {#if !avatarSrc}
      <NoneLabelAvatar name="T" />
    {/if}
    <h2>{author}</h2>
  </div>
</template>

<style>
  @import url('./style.css');
</style>

// client/src/components/PageHeader/PageHeader.vue
<script setup lang="ts">
import LabelAvatar from '../Avatar/LabelAvatar.vue';
import NoneLabelAvatar from '../Avatar/NoneLabelAvatar.vue';

type Props = {
  author?: string;
  avatarSrc?: string;
};
defineProps<Props>();
</script>

<template>
  <div class="page-header">
    <LabelAvatar
      v-if="avatarSrc"
      :src="avatarSrc"
      :alt="avatarSrc"
    />
    <NoneLabelAvatar
      v-else
      name="T"
    />
    <h2>{{ author }}</h2>
  </div>
</template>

<style scoped>
@import url('./style.css');
</style>
