// client/src/components/Button/AcceptButton.svelte
<script lang="ts">
  export let label: string = '';
  export let onAccept: () =>
    | void
    | boolean
    | Promise<void | boolean> = () => {};
</script>

<button
  on:click={onAccept}
  class="accept"
>
  <div class="content">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 15 15"
    >
      <path
        fill="currentColor"
        fill-rule="evenodd"
        d="M0 7.5a7.5 7.5 0 1 1 15 0a7.5 7.5 0 0 1-15 0Zm7.072 3.21l4.318-5.398l-.78-.624l-3.682 4.601L4.32 7.116l-.64.768l3.392 2.827Z"
        clip-rule="evenodd"
      />
    </svg>
    {label}
  </div>
</button>

<style>
  @import url('./style.css');
</style>

// client/src/components/Button/AcceptButton.vue
<script setup lang="ts">
type AcceptProps = {
  label?: string;
  onAccept?: () => void | boolean | Promise<void | boolean>;
};
defineProps<AcceptProps>();
</script>

<template>
  <button
    @click="onAccept"
    class="accept"
  >
    <div className="content">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 15 15"
      >
        <path
          fill="currentColor"
          fill-rule="evenodd"
          d="M0 7.5a7.5 7.5 0 1 1 15 0a7.5 7.5 0 0 1-15 0Zm7.072 3.21l4.318-5.398l-.78-.624l-3.682 4.601L4.32 7.116l-.64.768l3.392 2.827Z"
          clip-rule="evenodd"
        />
      </svg>
      {{ label }}
    </div>
  </button>
</template>

<style scoped>
@import url('./style.css');
</style>
