// client/src/components/Button/ClearButton.vue
<script setup lang="ts">
type ClearProps = {
  label?: string;
  onClear?: () => void | boolean | Promise<void | boolean>;
};
defineProps<ClearProps>();
</script>

<template>
  <button
    @click="onClear"
    class="close"
  >
    <div class="transparent-content">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
      >
        <path
          fill="currentColor"
          d="M18.3 5.71a.996.996 0 0 0-1.41 0L12 10.59L7.11 5.7A.996.996 0 1 0 5.7 7.11L10.59 12L5.7 16.89a.996.996 0 1 0 1.41 1.41L12 13.41l4.89 4.89a.996.996 0 1 0 1.41-1.41L13.41 12l4.89-4.89c.38-.38.38-1.02 0-1.4z"
        />
      </svg>
    </div>
  </button>
</template>

<style scoped>
@import url('./style.css');
</style>

// client/src/components/Button/ClearButton.svelte
<script lang="ts">
  export let onClear: () => void | boolean | Promise<void | boolean> = () => {};
</script>

<button
  on:click={onClear}
  class="close"
>
  <div class="transparent-content">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
    >
      <path
        fill="currentColor"
        d="M18.3 5.71a.996.996 0 0 0-1.41 0L12 10.59L7.11 5.7A.996.996 0 1 0 5.7 7.11L10.59 12L5.7 16.89a.996.996 0 1 0 1.41 1.41L12 13.41l4.89 4.89a.996.996 0 1 0 1.41-1.41L13.41 12l4.89-4.89c.38-.38.38-1.02 0-1.4z"
      />
    </svg>
  </div>
</button>

<style>
  @import url('./style.css');
</style>
