// client/src/components/Button/CreateButton.svelte
<script lang="ts">
  export let label: string = '';
  export let onCreate: () => void | Promise<void> = () => {};
</script>

<button
  on:click={onCreate}
  class="create"
>
  <div class="content">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 32 32"
    >
      <path
        fill="currentColor"
        d="M30 24h-4v-4h-2v4h-4v2h4v4h2v-4h4z"
      />
      <path
        fill="currentColor"
        d="M15.4 30L5 23.8c-.6-.4-1-1-1-1.7V9.9c0-.7.4-1.4 1-1.7l10-5.9c.3-.2.6-.3 1-.3s.7.1 1 .3l10 5.9c.6.4 1 1 1 1.7V16h-2V9.9L16 4L6 9.9v12.2l10.5 6.2l-1.1 1.7z"
      />
    </svg>
    {label}
  </div>
</button>

<style>
  @import url('./style.css');
</style>

// client/src/components/Button/CreateButton.vue
<script setup lang="ts">
type CreateProps = {
  label?: string;
  onCreate?: () => void | boolean | Promise<void | boolean>;
};
defineProps<CreateProps>();
</script>

<template>
  <button
    @click="onCreate"
    class="create"
  >
    <div class="content">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 32 32"
      >
        <path
          fill="currentColor"
          d="M30 24h-4v-4h-2v4h-4v2h4v4h2v-4h4z"
        />
        <path
          fill="currentColor"
          d="M15.4 30L5 23.8c-.6-.4-1-1-1-1.7V9.9c0-.7.4-1.4 1-1.7l10-5.9c.3-.2.6-.3 1-.3s.7.1 1 .3l10 5.9c.6.4 1 1 1 1.7V16h-2V9.9L16 4L6 9.9v12.2l10.5 6.2l-1.1 1.7z"
        />
      </svg>
      {{ label }}
    </div>
  </button>
</template>

<style scoped>
@import url('./style.css');
</style>
