// client/src/components/Button/LinkButton.vue
<script setup lang="ts">
type LinkProps = {
  label?: string;
  onNavigate?: () => void | boolean | Promise<void | boolean>;
};
defineProps<LinkProps>();
</script>

<template>
  <button
    @click="onNavigate"
    class="close"
  >
    <div class="transparent-content">{{ label }}</div>
  </button>
</template>

<style scoped>
@import url('./style.css');
</style>

// client/src/components/Button/LinkButton.svelte
<script lang="ts">
  export let label: string = '';
  export let onNavigate: () =>
    | void
    | Promise<void>
    | boolean
    | Promise<boolean> = () => {};
</script>

<button
  on:click={onNavigate}
  class="close"
>
  <div class="transparent-content">{label}</div>
</button>

<style>
  @import url('./style.css');
</style>
