// client/src/views/Navigator.vue
<script setup lang="ts">
import socket from '../socket';
import Grid from '../components/Grid.vue';
import GridItem from '../components/GridItem.vue';
import TextField from '../components/Input/TextField.vue';
import Modal from '../components/Modal/Modal.vue';
import ModalBody from '../components/Modal/ModalBody.vue';
import ModalFooter from '../components/Modal/ModalFooter.vue';
import PrimaryButton from '../components/PrimaryButton.vue';
import HorizontalSpacing from '../components/Spacing/HorizontalSpacing.vue';
import VerticalSpacing from '../components/Spacing/VerticalSpacing.vue';
import ErrorNotify from '../components/Toasty/ErrorNotify.vue';
import SuccessNotify from '../components/Toasty/SuccessNotify.vue';
import FriendList from '../components/User/FriendList.vue';
import StrangerList from '../components/User/StrangerList.vue';
import List from '../components/List.vue';
import ListItem from '../components/ListItem.vue';
import Friend from '../components/Friend.vue';
import FlipSquareLoading from '../components/Loading/FlipSquareLoading.vue';
import CancelIcon from '../components/Icon/CancelIcon.vue';
import CreateIcon from '../components/Icon/CreateIcon.vue';
import PeopleTeamIcon from '../components/Icon/PeopleTeamIcon.vue';
import FindIcon from '../components/Icon/FindIcon.vue';
import { reactive, ref } from 'vue';
import {
  Group,
  GroupResponse,
  InsensitiveResponseUserInfo,
  UserResponse,
} from '../types';
import { useAuth, useFriend, useGroup, useUser } from '../hooks';
import { DEBOUNCE_DURATION } from '../helpers';
import { tryOnMounted, tryOnUnmounted, useDebounceFn } from '@vueuse/core';

const users = ref<UserResponse[]>([]);
const friends = ref<InsensitiveResponseUserInfo[]>([]);
const groups = ref<GroupResponse[]>([]);
const members = ref<string[]>([]);
const onlineUsers = ref<string[]>([]);
const isLoadingFriends = ref(false);
const isLoadingGroups = ref(false);
const username = ref('');
const groupTitle = ref('');
const responseMessage = reactive({
  success: false,
  error: false,
});
const isOpenFindPeople = ref(false);
const isOpenCreateGroup = ref(false);

const { getUsersWithoutSelf, findUserByName } = useUser();
const { getFriendsByUserId, checkIfAdded, updateFriend } = useFriend();
const { userId, accessToken } = useAuth();
const { getGroupsByUser, createGroup } = useGroup();

async function retrieveFriends() {
  try {
    isLoadingFriends.value = true;
    const data = await getFriendsByUserId(userId, accessToken);
    friends.value = data;
    isLoadingFriends.value = false;
  } catch (e) {
    console.log(e);
  }
}

async function retrieveGroups() {
  try {
    isLoadingGroups.value = true;
    const data = await getGroupsByUser(userId, accessToken);
    groups.value = data;
    isLoadingGroups.value = false;
  } catch (e) {
    console.log(e);
  }
}

function findPeople() {
  isOpenFindPeople.value = true;
  getUsersWithoutSelf(userId, accessToken)
    .then(async (res: UserResponse[]) => {
      const filteredAddedUsers = [];
      for await (const user of res) {
        const isAdded = await checkIfAdded(userId, user._id as string);
        if (!isAdded) filteredAddedUsers.push(user);
      }
      users.value = filteredAddedUsers;
    })
    .catch((err) => console.log(err));
}

function addFriend(filteredUserId: string) {
  updateFriend({ userId, friendId: filteredUserId, accessToken })
    .then(() => {
      const remainUsers = users.value.filter(
        (user) => user._id !== filteredUserId,
      );
      users.value = remainUsers;
    })
    .catch((err) => console.log(err));
}
const debounceAddFriend = useDebounceFn(addFriend, DEBOUNCE_DURATION);

function filterUser() {
  const value = username.value.trim();
  if (value.length === 0) return;
  findUserByName({ keyword: value, userId, accessToken })
    .then((res) => (users.value = res))
    .catch((err) => console.log(err));
}
const debounceFilterUser = useDebounceFn(filterUser, DEBOUNCE_DURATION);

function handleCreateGroup() {
  if (!groupTitle.value) return;
  if (groupTitle.value.length === 0) {
    responseMessage.error = true;
    return;
  }
  const group: Group = {
    title: groupTitle.value,
    owner: userId,
    users: members.value,
  };
  createGroup(group, accessToken)
    .then(() => {
      responseMessage.success = true;
      members.value = [];
    })
    .catch((err) => console.log(err));
}
const debounceCreateGroup = useDebounceFn(handleCreateGroup, DEBOUNCE_DURATION);

function handleAddToGroup(user: string) {
  if (members.value.length === 0) {
    members.value.push(user);
    return;
  }
  if (!members.value.includes(user)) {
    members.value.push(user);
    return;
  }
  const filtered = members.value.filter((member) => member !== user);
  members.value = filtered;
}
const debounceAddToGroup = useDebounceFn(handleAddToGroup, DEBOUNCE_DURATION);

function setOnline(userIds: string[]) {
  onlineUsers.value = userIds;
}

tryOnMounted(() => {
  socket.connect();
  socket.emit('online', { isOnline: true, userId });
  socket.on('user-onlines', setOnline);
  retrieveFriends();
  retrieveGroups();
});

tryOnUnmounted(() => {
  socket.disconnect();
  socket.off('online', () => {});
  socket.off('user-onlines', setOnline);
});
</script>

<template>
  <SuccessNotify
    v-show="responseMessage.success"
    message="Created group!"
    :duration="3000"
    @reset="responseMessage.success = false"
  />
  <ErrorNotify
    v-show="responseMessage.error"
    message="Cannot create group without a title!"
    :duration="3000"
    @reset="responseMessage.error = false"
  />
  <Grid>
    <GridItem type="side">
      <HorizontalSpacing floated>
        <PrimaryButton
          label="Find"
          @action="findPeople"
        >
          <FindIcon />
        </PrimaryButton>
        <PrimaryButton
          label="Create Group"
          @action="isOpenCreateGroup = true"
        >
          <CreateIcon />
        </PrimaryButton>
      </HorizontalSpacing>
      <Modal
        :open="isOpenFindPeople"
        title="Find People"
        @close="isOpenFindPeople = false"
      >
        <ModalBody>
          <TextField
            label="Username"
            name="room-input"
            v-model:value="username"
            @clear="username = ''"
            @enter="debounceFilterUser"
          />
          <HorizontalSpacing>
            <StrangerList
              v-for="user in users"
              :key="user._id"
              :uid="user._id"
              :name="user.fullname"
              :is-self="user._id === userId"
              @action="() => debounceAddFriend(user._id)"
            />
          </HorizontalSpacing>
        </ModalBody>
        <ModalFooter>
          <PrimaryButton
            label="Cancel"
            @action="isOpenFindPeople = false"
          >
            <CancelIcon />
          </PrimaryButton>
        </ModalFooter>
      </Modal>
      <Modal
        :open="isOpenCreateGroup"
        title="Create a Group"
        @close="isOpenCreateGroup = false"
      >
        <ModalBody>
          <TextField
            label="Title"
            name="group-input"
            @clear="groupTitle = ''"
          />
          <HorizontalSpacing>
            <FriendList
              v-for="friend in friends"
              :key="friend._id"
              :uid="friend._id"
              :name="friend.fullname"
              :temporaryDisabled="members.includes(friend._id)"
              @action="() => debounceAddToGroup(friend._id)"
            />
          </HorizontalSpacing>
          <VerticalSpacing>
            <h3 class="member-label">
              <PeopleTeamIcon />
              Members: {{ members.length }}
            </h3>
          </VerticalSpacing>
        </ModalBody>
        <ModalFooter>
          <PrimaryButton
            label="Create"
            @action="debounceCreateGroup"
          >
            <CreateIcon />
          </PrimaryButton>
          <PrimaryButton
            label="Cancel"
            @action="isOpenCreateGroup = false"
          >
            <CancelIcon />
          </PrimaryButton>
        </ModalFooter>
      </Modal>
      <List>
        <ListItem>
          <Friend
            invisible
            avatar-src=""
            opponent-name=""
          />
          <FlipSquareLoading v-if="isLoadingFriends || isLoadingGroups" />
          <template v-else>
            <Friend
              v-for="friend in friends"
              :key="friend._id"
              :opponentName="friend.fullname"
              :latestMessage="
                onlineUsers.includes(friend._id) ? 'Online' : 'Offline'
              "
              @action="$router.replace({ path: `/@chat/${friend._id}` })"
            />
            <Friend
              v-for="group in groups"
              :key="group._id"
              :opponentName="group.title"
              :latestMessage="`${group.lastMessage.sender && '@'}${
                group.lastMessage.sender
              }${group.lastMessage.sender && ': '}${group.lastMessage.content}`"
              @action="$router.replace({ path: `/@chat/group/${group._id}` })"
            />
          </template>
        </ListItem>
      </List>
    </GridItem>
    <GridItem type="article">
      <RouterView :key="$route.fullPath" />
    </GridItem>
  </Grid>
</template>

<style scoped>
.member-label {
  background: var(--darker-bg);
  border-radius: '10px';
  padding: '.5rem';
  display: 'flex';
  gap: '.2rem';
}
</style>

// client/src/views/Navigator/index.tsx
import React, { createRef, useEffect, useState } from 'react';
import { debounce } from 'lodash';
import { Outlet, useNavigate } from 'react-router-dom';
import { useQuery } from 'react-query';
import { DEBOUNCE_DURATION } from '../../helpers';
import { useAuth, useFriend, useGroup, useUser } from '../../hooks';
import { Group, GroupResponse, User as TUser } from '../../types';
import {
  Button,
  CancelIcon,
  Container,
  CreateIcon,
  FindIcon,
  Input,
  List,
  Message,
  Modal,
  PeopleTeamIcon,
  Spacing,
  User,
  Loading,
  Notify
} from '../../components';
import socket from '../../socket';

export function Navigator() {
  const [onlineUsers, setOnlineUsers] = useState<string[]>([])
  const [users, setUsers] = useState<Array<Omit<TUser, 'password'>>>([]);
  const [openFindPeople, setOpenFindPeople] = useState(false);
  const [openCreateGroup, setOpenCreateGroup] = useState(false);
  const [isCreatedLoading, setIsCreatedLoading] = useState(false);
  const [isSuccessCreated, setIsSuccessCreated] = useState(false);
  const [isErrorCreated, setIsErrorCreated] = useState(false);
  const [members, setMembers] = useState<string[]>([]);

  const navigate = useNavigate();
  const { getUsersWithoutSelf, findUserByName } = useUser();
  const { getFriendsByUserId, checkIfAdded, updateFriend } = useFriend();
  const { userId, accessToken } = useAuth();
  const { getGroupsByUser, createGroup } = useGroup();

  const groupTitle = createRef<HTMLInputElement>();
  const username = createRef<HTMLInputElement>();
  const { data: friends, isLoading: isLoadingFriends } = useQuery(
    'FriendsByUserId',
    () => getFriendsByUserId(userId, accessToken),
    {
      staleTime: 5000,
      cacheTime: 30000,
      refetchOnMount: true
    },
  );
  const { data: groups, isLoading: isLoadingGroups } = useQuery(
    'GroupsByUserId',
    () => getGroupsByUser(userId, accessToken),
    {
      staleTime: 5000,
      cacheTime: 30000,
      refetchOnMount: true
    },
  );

  function findPeople() {
    setOpenFindPeople(true);
    getUsersWithoutSelf(userId, accessToken)
      .then(async (res: TUser[]) => {
        const filteredAddedUsers = [];
        for await (const user of res) {
          const isAdded = await checkIfAdded(userId, user._id as string);
          if (!isAdded) filteredAddedUsers.push(user);
        }
        setUsers(filteredAddedUsers);
      })
      .catch((err) => console.log(err));
  }

  function addFriend(filteredUserId: string) {
    updateFriend({ userId, friendId: filteredUserId, accessToken })
      .then(() => {
        const remainUsers = users.filter((user) => user._id !== filteredUserId);
        setUsers(remainUsers);
      })
      .catch((err) => console.log(err));
  }
  const debounceAddFriend = debounce(addFriend, DEBOUNCE_DURATION);

  function filterUser() {
    const value = `${username.current?.value}`.trim();
    if (value.length === 0) return;
    findUserByName({ keyword: value, userId, accessToken })
      .then((res) => setUsers(res))
      .catch((err) => console.log(err));
  }
  const debounceFilterUser = debounce(filterUser, DEBOUNCE_DURATION);

  function handleCreateGroup() {
    if (!groupTitle.current)
      return
    setIsCreatedLoading(true);
    if (groupTitle.current.value.length === 0) {
      setIsCreatedLoading(false);
      setIsErrorCreated(true)
      return
    }
    const group: Group = {
      title: groupTitle.current.value,
      owner: userId,
      users: members,
    };
    createGroup(group, accessToken)
      .then(() => {
        setIsCreatedLoading(false);
        setIsSuccessCreated(true)
        setOpenCreateGroup(false);
        setMembers([]);
      })
      .catch((err) => console.log(err));
  }
  const debounceCreateGroup = debounce(handleCreateGroup, DEBOUNCE_DURATION);

  function handleAddToGroup(user: string) {
    if (members.length === 0) {
      setMembers((prev) => [...prev, user]);
      return;
    }
    if (!members.includes(user)) {
      setMembers((prev) => [...prev, user]);
      return;
    }
    setMembers((prev) => prev.filter((member) => member !== user));
  }
  const debounceAddToGroup = debounce(handleAddToGroup, DEBOUNCE_DURATION);

  useEffect(() => {
    socket.connect()
    function setOnline(userIds: string[]) {
      setOnlineUsers(userIds)
    }
    socket.emit('online', { isOnline: true, userId })
    socket.on('user-onlines', setOnline)
    return () => {
      socket.disconnect()
      socket.off('online', () => { })
      socket.off('user-onlines', setOnline)
    }
  }, [])

  return (
    <React.Fragment>
      {isSuccessCreated && <Notify.Success message='Created group!' duration={3000} reset={() => setIsSuccessCreated(false)} />}
      {isErrorCreated && <Notify.Error message='Cannot create group without a title!' duration={3000} reset={() => setIsErrorCreated(false)} />}
      <Container.Grid>
        <Container.GridItem type='side'>
          <Spacing.Horizontal floated>
            <Button.Send
              label='Find'
              icon={<FindIcon />}
              onSend={() => findPeople()}
            />
            <Button.Send
              label='Create Group'
              icon={<CreateIcon />}
              onSend={() => setOpenCreateGroup(true)}
            />
          </Spacing.Horizontal>
          <Modal.Customizable
            open={openFindPeople}
            title='Find People'
            onClose={() => setOpenFindPeople(false)}
          >
            <Modal.ContentBody>
              <Input.Search
                ref={username}
                label='User Name'
                name='room-input'
                value={username.current?.value}
                onClear={() => {
                  if (username.current) username.current.value = '';
                }}
                onEnter={debounceFilterUser}
              />
              <Spacing.Horizontal>
                {users &&
                  users.map((user, index) => (
                    <User.StrangerList
                      key={index}
                      uid={user._id as string}
                      name={user.fullname}
                      onAction={() => debounceAddFriend(user._id as string)}
                      isSelf={user._id === userId}
                    />
                  ))}
              </Spacing.Horizontal>
            </Modal.ContentBody>
            <Modal.ActionFooter>
              <Button.Cancel
                label='Cancel'
                icon={<CancelIcon />}
                onCancel={() => setOpenFindPeople(false)}
              />
            </Modal.ActionFooter>
          </Modal.Customizable>
          <Modal.Customizable
            open={openCreateGroup}
            title='Create a group'
            onClose={() => setOpenCreateGroup(false)}
          >
            {isCreatedLoading ? (
              <Loading.Swap />
            ) : (
              <React.Fragment>
                <Modal.ContentBody>
                  <Input.Text
                    ref={groupTitle}
                    label='Group Title'
                    name='group-creator'
                    value={groupTitle.current?.value}
                    onClear={() => {
                      if (groupTitle.current) groupTitle.current.value = '';
                    }}
                    onEnter={debounceCreateGroup}
                  />
                  <Spacing.Vertical>
                    <h3
                      style={{
                        background: 'var(--darker-bg)',
                        borderRadius: '10px',
                        padding: '.5rem',
                        display: 'flex',
                        gap: '.2rem',
                      }}
                    >
                      <PeopleTeamIcon />
                      {`Members: ${members.length}`}
                    </h3>
                  </Spacing.Vertical>
                  <Spacing.Horizontal>
                    {isLoadingFriends ? (
                      <Loading.Swap />
                    ) : (
                      friends.map(
                        (user: Omit<TUser, 'password'>, index: number) => (
                          <User.FriendList
                            key={index}
                            uid={user._id as string}
                            name={user.fullname}
                            onAction={() =>
                              debounceAddToGroup(user._id as string)
                            }
                            temporaryDisabled={members.includes(
                              user._id as string,
                            )}
                          />
                        ),
                      )
                    )}
                  </Spacing.Horizontal>
                </Modal.ContentBody>
                <Modal.ActionFooter>
                  <Button.Accept
                    label='Create'
                    icon={<CreateIcon />}
                    onAccept={debounceCreateGroup}
                  />
                  <Button.Cancel
                    label='Cancel'
                    icon={<CancelIcon />}
                    onCancel={() => setOpenCreateGroup(false)}
                  />
                </Modal.ActionFooter>
              </React.Fragment>
            )}
          </Modal.Customizable>
          <List.Box>
            <List.Item>
              <Message.Card
                avatarSrc=''
                opponentName=''
                latestMessage=''
                onAction={() => { }}
                invisible
              />
              {
                isLoadingFriends || isLoadingGroups
                  ? <Loading.FlipSquare partialStyle />
                  : <React.Fragment>
                    {
                      friends.map(
                        (friend: Omit<TUser, 'password'>, index: number) => (
                          <Message.Card
                            key={index}
                            avatarSrc=''
                            opponentName={friend.fullname}
                            latestMessage={onlineUsers.includes(friend._id as string) ? 'Online' : 'Offline'}
                            onAction={() => navigate(`/chat/${friend._id}`)}
                          />
                        ),
                      )
                    }
                    {
                      groups.map((group: GroupResponse, index: number) => (
                        <Message.Card
                          key={index}
                          avatarSrc=''
                          opponentName={group.title}
                          latestMessage={`${group.lastMessage.sender && '@'}${group.lastMessage.sender
                            }${group.lastMessage.sender && ': '}${group.lastMessage.content
                            }`}
                          onAction={() => navigate(`/chat/group/${group._id}`)}
                        />
                      ))
                    }
                  </React.Fragment>
              }
            </List.Item>
          </List.Box>
        </Container.GridItem>

        <Container.GridItem type='article'>
          <Outlet />
        </Container.GridItem>
      </Container.Grid>
    </React.Fragment>
  );
}
