// client/src/components/ChatBox/ChatBox.svelte
<script lang="ts">
  type Types = 'container' | 'fluid';
  export let type: Types = 'container';
</script>

{#if type === 'container'}
  <div class="container">
    <slot />
  </div>
{/if}

{#if type === 'fluid'}
  <div class="fluid">
    <slot />
  </div>
{/if}

<style>
  @import url('./style.css');
</style>

// client/src/components/ChatBox/ChatBox.vue
<script setup lang="ts">
type Props = {
  type?: 'container' | 'fluid';
};
defineProps<Props>();
</script>

<template>
  <div
    v-if="type === 'container'"
    class="container"
  >
    <slot />
  </div>
  <div
    v-else
    class="container"
  >
    <slot />
  </div>
</template>

<style>
@import url('./style.css');
</style>
