// client/src/components/ChatBox/ChatBody.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  let chatBody: HTMLDivElement;

  function onScrollDown() {
    chatBody.scrollIntoView({
      behavior: 'smooth',
      block: 'end',
      inline: 'nearest',
    });
  }

  onMount(() => {
    onScrollDown();
  });
</script>

<div class="inner-box">
  <div
    bind:this={chatBody}
    class="chat"
  >
    <slot />
  </div>
</div>

// client/src/components/ChatBox/ChatBody.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { triggerScrollDown } from '../../helpers';

const chatBody = ref<HTMLDivElement | null>(null);
function onScrollDown() {
  chatBody.value?.scrollIntoView({
    behavior: 'smooth',
    block: 'end',
    inline: 'nearest',
  });
}
watch(triggerScrollDown, () => {
  onScrollDown();
});
</script>

<template>
  <div class="inner-box">
    <div
      ref="chatBody"
      class="chat"
    >
      <slot />
    </div>
  </div>
</template>
