// client/src/components/ChatBox/index.tsx
import './style.css';
import React, { ReactNode } from 'react';

interface Props {
  children: ReactNode;
  type?: 'container' | 'fluid';
}

export const Chat = {
  Box: ({ children, type }: Props) => (
    <React.Fragment>
      {type === 'container'
        ? (
          <div className='container'>
            {children}
          </div>
        ) : (
          <div className='fluid'>
            {children}
          </div>
        )
      }
    </React.Fragment>
  ),
  Header: ({ children }: Props) => (
    <div className='inner-box-header'>
      <div className='chat-header'>{children}</div>
    </div>
  ),
  Body: ({ children }: Props) => (
    <div className='inner-box'>
      <div className='chat'>{children}</div>
    </div>
  ),
  Footer: ({ children }: Props) => (
    <div className='inner-box-footer'>
      <div className='chat-footer'>{children}</div>
    </div>
  ),
};

// client/src/components/ChatBox/ChatBox.vue
<script setup lang="ts">
type Props = {
  type?: 'container' | 'fluid';
};
defineProps<Props>();
</script>

<template>
  <div
    v-if="type === 'container'"
    class="container"
  >
    <slot />
  </div>
  <div
    v-else
    class="container"
  >
    <slot />
  </div>
</template>

<style>
@import url('./style.css');
</style>
